global:
  environment: prod

backend:
  replicaCount: 3

frontend:
  replicaCount: 2

ingress:
  enabled: true
  hosts:
    - host: todo-app.prod.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - todo-app.prod.example.com
      secretName: todo-app-tls
