global:
  environment: dev

backend:
  replicaCount: 1

frontend:
  replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: todo-app.dev.local
      paths:
        - path: /
          pathType: Prefix
