global:
  environment: prod

backend:
  replicaCount: 3

frontend:
  replicaCount: 2

ingress:
  enabled: true
  hosts:
    - host: todo-app.com
  tls:
    - hosts:
        - todo-app.com
      secretName: todo-app-tls
