global:
  environment: dev

backend:
  replicaCount: 1

frontend:
  replicaCount: 1

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: www.todo-app.lat
  tls:
    - hosts:
        - www.todo-app.lat
      secretName: todo-app-tls

