global:
  environment: dev

backend:
  replicaCount: 1
  image:
    repository: myacr.azurecr.io/todo-app-server
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 4000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    corsOrigin: "*"

frontend:
  replicaCount: 1
  image:
    repository: myacr.azurecr.io/todo-app-client
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 80
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

ingress:
  className: nginx
  tls: []
