apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-app.fullname" . }}-frontend
  labels:
    app: {{ include "todo-app.fullname" . }}
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "todo-app.fullname" . }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ include "todo-app.fullname" . }}
        component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          env:
            - name: VITE_API_BASE_URL
              value: "http://{{ include "todo-app.fullname" . }}-backend:{{ .Values.backend.service.port }}"
